CREATE DATABASE QuanLiVatTu4;
USE QuanLiVatTu4;
CREATE TABLE PhieuXuat(
    SoPX INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NgayXuat DATETIME NOT NULL
);

CREATE TABLE VatTu(
    MaVTu INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    TenVTu VARCHAR(30) NOT NULL
);

CREATE TABLE ChiTietPhieuXuat(
    DGXuat VARCHAR(30) NOT NULL ,
    SLXuat INT NOT NULL ,
    MaVtu INT NOT NULL ,
    SoPX INT NOT NULL ,
    FOREIGN KEY (MaVtu) REFERENCES VatTu(MaVTu),
    FOREIGN KEY (SoPX) REFERENCES PhieuXuat(SoPX)
);

CREATE TABLE NhaCC(
   MaNCC INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
   TenNCC VARCHAR(40) NOT NULL ,
   DiaChi VARCHAR(50) NOT NULL ,
   SDT VARCHAR(30)    NOT NULL
);

CREATE TABLE DonDH(
    SoDH INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NgayDH DATETIME NOT NULL,
    MaNCC INT NOT NULL,
    FOREIGN KEY (MaNCC) REFERENCES NhaCC(MaNCC)
);

CREATE TABLE ChiTietDonDatHang(
    MaVTu INT NOT NULL,
    SoDH INT NOT NULL,
    FOREIGN KEY (MaVTu) REFERENCES VatTu(MaVTu),
    FOREIGN KEY (SoDH) REFERENCES DonDH(SoDH)
);

CREATE TABLE PhieuNhap(
    SoPN INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NgayNhap DATETIME NOT NULL
);

CREATE TABLE ChiTietPhieuNhap(
    DGNhap VARCHAR(30) NOT NULL ,
    SLNhap INT NOT NULL ,
    SoPN INT NOT NULL,
    MaVTu INT NOT NULL,
    FOREIGN KEY (SoPN) REFERENCES PhieuNhap(SoPN),
    FOREIGN KEY (MaVTu) REFERENCES VatTu(MaVTu)
);






